on:
  push:
    branches:
      - master



jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: "before printing the folder containts"
        run: ls

      - uses: actions/checkout@v3

      - name: "after printing the folder containts"
        run: ls -a

